apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "crawlerbeast9870@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "qicz tbfd ahtm"
type: Opaque

# Passw0rd@1234